# Sample .travis.yml for R projects

language: r
r:
  - oldrel
  - release
  - devel
# Create a build matrix that will test package with an empty DISPLAY value
# (making the clipboard unavailable) and a correctly-configured DISPLAY (making
# the clipboard available)
env:
  - DISPLAY=""
  - DISPLAY=:99.0
warnings_are_errors: true
cache: packages
sudo: false
r_check_revdep: false

# Install xclip
addons:
  apt:
    packages:
      - xclip

# Ensure xclip can still run headlessly
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
